//====================================================================================================================================================
// Copyright 2025 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.25.00.05
// Generated on Sunday, February 16, 2025 10:12:00 PM

#pragma once

#include <memory>
#include <string>

// FRC Includes
#include <networktables/NetworkTable.h>

#include "ctre/phoenix6/TalonFXS.hpp"
#include "ctre/phoenix6/controls/Follower.hpp"
#include "ctre/phoenix6/configs/Configs.hpp"
#include <frc/DigitalInput.h>
#include <frc/filter/Debouncer.h>

#include "mechanisms/base/BaseMech.h"
#include "state/StateMgr.h"
#include "state/IRobotStateChangeSubscriber.h"
#include "mechanisms/controllers/ControlData.h"
#include "state/RobotStateChanges.h"

#include "configs/RobotElementNames.h"
#include "configs/MechanismConfigMgr.h"

#include "RobotIdentifier.h"

class IntakeManager : public BaseMech, public StateMgr, public IRobotStateChangeSubscriber
{
public:
	enum STATE_NAMES
	{
		STATE_OFF,
		STATE_INTAKE,
		STATE_HOLD,
		STATE_TRANSFER_IN,
		STATE_TRANSFER_OUT,
		STATE_PROCESS,
		STATE_EXPEL
	};

	IntakeManager(RobotIdentifier activeRobotId);
	IntakeManager() = delete;
	~IntakeManager() = default;

	void CreatePRACTICE_BOT9999();
	void CreateCOMP_BOT302();
	void InitializePRACTICE_BOT9999();
	void InitializeCOMP_BOT302();

	/// @brief Set the control constants (e.g. PIDF values).
	/// @param indentifier the motor controller usage to identify the motor
	/// @param slot position on the motor controller to set
	/// @param pid control data / constants
	virtual void SetControlConstants(RobotElementNames::MOTOR_CONTROLLER_USAGE indentifier, int slot, ControlData pid);

	/// @brief update the output to the mechanism using the current controller and target value(s)
	virtual void Update();

	void UpdateTargetIntakePercentOutput(double percentOut)
	{
		m_IntakePercentOutput.Output = percentOut;
		m_IntakeActiveTarget = &m_IntakePercentOutput;
	}
	void UpdateTargetIntakePercentOutput(double percentOut, bool enableFOC)
	{
		m_IntakePercentOutput.Output = percentOut;
		m_IntakePercentOutput.EnableFOC = enableFOC;
		m_IntakeActiveTarget = &m_IntakePercentOutput;
	}
	void UpdateTargetExtenderPositionDegree(units::angle::turn_t position)
	{
		m_ExtenderPositionDegree.Position = position;
		m_ExtenderActiveTarget = &m_ExtenderPositionDegree;
	}

	void SetPIDExtenderPositionDegree();

	virtual bool IsAtMinPosition(RobotElementNames::MOTOR_CONTROLLER_USAGE identifier) const;
	virtual bool IsAtMaxPosition(RobotElementNames::MOTOR_CONTROLLER_USAGE identifier) const;

	void CreateAndRegisterStates();
	void Cyclic();
	void RunCommonTasks() override;

	RobotIdentifier getActiveRobotId() { return m_activeRobotId; }

	ctre::phoenix6::hardware::TalonFXS *GetIntake() const { return m_Intake; }
	ctre::phoenix6::hardware::TalonFXS *GetExtender() const { return m_Extender; }
	bool GetIntakeSensorState() const { return m_IntakeSensor->Get(); }
	ControlData *GetPercentOutput() const { return m_PercentOutput; }
	ControlData *GetPositionDegree() const { return m_PositionDegree; }

	bool GetFailedSensor() const { return m_failedSensorLatch; }

	static std::map<std::string, STATE_NAMES> stringToSTATE_NAMESEnumMap;

	void SetCurrentState(int state, bool run) override;

protected:
	RobotIdentifier m_activeRobotId;
	std::string m_ntName;
	std::string m_tuningIsEnabledStr;
	bool m_tuning = false;
	std::shared_ptr<nt::NetworkTable> m_table;

	ControlData *GetControlData(std::string name) override;

private:
	std::unordered_map<std::string, STATE_NAMES> m_stateMap;

	ctre::phoenix6::hardware::TalonFXS *m_Intake;
	ctre::phoenix6::hardware::TalonFXS *m_Extender;
	frc::DigitalInput *m_IntakeSensor;
	ControlData *m_PercentOutput;
	ControlData *m_PositionDegree;

	void CheckForTuningEnabled();
	void ReadTuningParamsFromNT();
	void PushTuningParamsToNT();

	void InitializeTalonFXSIntakePRACTICE_BOT9999();
	void InitializeTalonFXSExtenderPRACTICE_BOT9999();
	void InitializeTalonFXSIntakeCOMP_BOT302();
	void InitializeTalonFXSExtenderCOMP_BOT302();

	ctre::phoenix6::controls::DutyCycleOut m_IntakePercentOutput{0.0};
	ctre::phoenix6::controls::PositionVoltage m_ExtenderPositionDegree{units::angle::turn_t(0.0)};
	ctre::phoenix6::controls::ControlRequest *m_IntakeActiveTarget;
	ctre::phoenix6::controls::ControlRequest *m_ExtenderActiveTarget;

	bool m_failedSensorLatch = false;
	bool m_manualModeButtonReleased = true;
};