$$_COPYRIGHT_$$
$$_GEN_NOTICE_$$

#pragma once

enum RobotIdentifier
{
    CHASSISBOT_9998 = 9998,
    CHASSIS_BOT_9997 = 9997,
    $$_ROBOT_CONFIGURATIONS_NAMES_ENUMS_$$

        MAX_ROBOT_IDENTIFIERS
};