<<<<<<< HEAD
// clang-format off
//====================================================================================================================================================
// Copyright 2025 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 1.2.3.1
// Generated on Tuesday, February 6, 2025 9:48:58 PM
=======
#pragma once
>>>>>>> cb932b3feaa0c74ca84a11557fb9b5ff6de219c3

#include <string>

using std::string;

<<<<<<< HEAD
#pragma once

class DragonTestCase
{
public:
	virtual void SetUp() =0;

private:
	DragonTestCase(string testSuiteName, string testCaseName);
	~DragonTestCase();
=======
class DragonTestCase
{
public:
    DragonTestCase(string testSuiteName, string testCaseName);
    virtual void SetUp() = 0;
    virtual bool Run() = 0;
    virtual void CompareAndReport() = 0;

private:
    string m_testCaseName;
>>>>>>> cb932b3feaa0c74ca84a11557fb9b5ff6de219c3
};