//====================================================================================================================================================
// Copyright 2025 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.25.00.05
// Generated on Sunday, February 16, 2025 5:48:03 PM

#pragma once

#include <memory>
#include <string>

// FRC Includes
#include <networktables/NetworkTable.h>
#include "wpi/DataLog.h"

#include "ctre/phoenix6/TalonFX.hpp"
#include "ctre/phoenix6/TalonFXS.hpp"
#include "ctre/phoenix6/controls/Follower.hpp"
#include "ctre/phoenix6/configs/Configs.hpp"
#include "ctre/phoenix6/SignalLogger.hpp"
#include <frc/DigitalInput.h>

#include "mechanisms/base/BaseMech.h"
#include "state/StateMgr.h"
#include "state/IRobotStateChangeSubscriber.h"
#include "mechanisms/controllers/ControlData.h"
#include "state/RobotStateChanges.h"

#include "configs/RobotElementNames.h"
#include "configs/MechanismConfigMgr.h"
#include "utils/logging/signals/DragonDataLogger.h"

#include "RobotIdentifier.h"

using ctre::phoenix6::SignalLogger;

class ClimberManager : public BaseMech, public StateMgr, public DragonDataLogger, public IRobotStateChangeSubscriber
{
public:
	enum STATE_NAMES
	{
		STATE_INIT,
		STATE_OFF,
		STATE_MANUAL_CLIMB,
		STATE_AUTO_CLIMB,
		STATE_DELIVER_CLIMBER
	};

	ClimberManager(RobotIdentifier activeRobotId);
	ClimberManager() = delete;
	~ClimberManager() = default;

	void CreatePRACTICE_BOT9999();
	void CreateCOMP_BOT302();
	void InitializePRACTICE_BOT9999();
	void InitializeCOMP_BOT302();

	/// @brief Set the control constants (e.g. PIDF values).
	/// @param indentifier the motor controller usage to identify the motor
	/// @param slot position on the motor controller to set
	/// @param pid control data / constants
	virtual void SetControlConstants(RobotElementNames::MOTOR_CONTROLLER_USAGE indentifier, int slot, ControlData pid);

	/// @brief update the output to the mechanism using the current controller and target value(s)
	virtual void Update();

	void UpdateTargetClimberPercentOut(double percentOut)
	{
		m_ClimberPercentOut.Output = percentOut;
		m_ClimberActiveTarget = &m_ClimberPercentOut;
	}
	void UpdateTargetClimberPositionDegree(units::angle::turn_t position)
	{
		m_ClimberPositionDegree.Position = position;
		m_ClimberActiveTarget = &m_ClimberPositionDegree.WithSlot(0);
	}
	void UpdateTargetClimberPositionDegreeUp(units::angle::turn_t position)
	{
		m_ClimberPositionDegreeUp.Position = position;
		m_ClimberActiveTarget = &m_ClimberPositionDegreeUp.WithSlot(1);
	}
	void UpdateTargetExtenderPositionDegree(units::angle::turn_t position)
	{
		m_ExtenderPositionDegree.Position = position;
		m_ExtenderActiveTarget = &m_ExtenderPositionDegree;
	}
	void UpdateTargetExtenderPercentOutput(double percentOut)
	{
		m_ExtenderPercentOutput.Output = percentOut;
		m_ExtenderActiveTarget = &m_ExtenderPercentOutput;
	}

	virtual bool IsAtMinPosition(RobotElementNames::MOTOR_CONTROLLER_USAGE identifier) const;
	virtual bool IsAtMaxPosition(RobotElementNames::MOTOR_CONTROLLER_USAGE identifier) const;

	void CreateAndRegisterStates();
	void Cyclic();
	void RunCommonTasks() override;
	void DataLog(uint64_t timestamp) override;

	bool AtTarget();

	bool IsClimbMode() const { return m_climbMode == RobotStateChanges::ClimbMode::ClimbModeOn; }
	bool IsTeleop() { return m_gameMode == RobotStateChanges::GamePeriod::Teleop; };
	void NotifyStateUpdate(RobotStateChanges::StateChange stchange, int value) override;

	RobotIdentifier getActiveRobotId() { return m_activeRobotId; }

	ctre::phoenix6::hardware::TalonFX *GetClimber() const { return m_Climber; }
	ctre::phoenix6::hardware::TalonFXS *GetExtender() const { return m_Extender; }
	bool GetClimberSensorState() const { return !m_ClimberSensor->Get(); }
	ControlData *GetPositionDegree() const { return m_PositionDegree; }
	ControlData *GetPercentOut() const { return m_PercentOut; }
	ControlData *GetPositionDegreeUp() const { return m_PositionDegreeUp; }

	static std::map<std::string, STATE_NAMES> stringToSTATE_NAMESEnumMap;

	void SetCurrentState(int state, bool run) override;

protected:
	RobotIdentifier m_activeRobotId;
	std::string m_ntName;

	ControlData *GetControlData(std::string name) override;

private:
	std::unordered_map<std::string, STATE_NAMES> m_stateMap;

	ctre::phoenix6::hardware::TalonFX *m_Climber;
	ctre::phoenix6::hardware::TalonFXS *m_Extender;
	frc::DigitalInput *m_ClimberSensor;
	ControlData *m_PositionDegree;
	ControlData *m_PercentOut;
	ControlData *m_PositionDegreeUp;

	RobotStateChanges::GamePeriod m_gameMode;
	RobotStateChanges::ClimbMode m_climbMode;

	void InitializeTalonFXClimberPRACTICE_BOT9999();
	void InitializeTalonFXClimberCOMP_BOT302();
	void InitializeTalonFXSExtenderCOMP_BOT302();
	void InitializeTalonFXSExtenderPRACTICE_BOT9999();

	ctre::phoenix6::controls::DutyCycleOut m_ClimberPercentOut{0.0};
	ctre::phoenix6::controls::PositionTorqueCurrentFOC m_ClimberPositionDegree{units::angle::turn_t(0.0)};
	ctre::phoenix6::controls::PositionTorqueCurrentFOC m_ClimberPositionDegreeUp{units::angle::turn_t(0.0)};
	ctre::phoenix6::controls::ControlRequest *m_ClimberActiveTarget;
	ctre::phoenix6::controls::ControlRequest *m_ExtenderActiveTarget;

	void InitializeLogging();
	wpi::log::DoubleLogEntry m_ExtenderLogEntry;
	wpi::log::DoubleLogEntry m_ExtenderTargetLogEntry;
	wpi::log::DoubleLogEntry m_ExtenderPowerLogEntry;
	wpi::log::DoubleLogEntry m_ExtenderEnergyLogEntry;

	units::turn_t m_extenderThreshold = units::turn_t(3.0);

	ctre::phoenix6::controls::DutyCycleOut m_ExtenderPercentOutput{0.0};
	ctre::phoenix6::controls::PositionVoltage m_ExtenderPositionDegree{units::angle::turn_t(0.0)};

	frc::Timer m_powerTimer;
	double m_power = 0.0;
	double m_energy = 0.0;
	double m_totalEnergy = 0.0;
	double m_totalWattHours = 0.0;

	auto LogClimber(std::string name, std::string units, double value) { return SignalLogger::WriteDouble(name, value, units, units::time::second_t(0.0_s)); }
	auto LogClimberTarget(std::string name, std::string units, double value) { return SignalLogger::WriteDouble(name, value, units, units::time::second_t(0.0_s)); }
	auto LogClimberPower(std::string name, std::string units, double value) { return SignalLogger::WriteDouble(name, value, units, units::time::second_t(0.0_s)); }
	auto LogClimberEnergy(std::string name, std::string units, double value) { return SignalLogger::WriteDouble(name, value, units, units::time::second_t(0.0_s)); }
	auto LogClimberManagerTotalEnergy(std::string name, std::string units, int value) { return SignalLogger::WriteDouble(name, value, units, units::time::second_t(0.0_s)); }
	auto LogClimberManagerTotalWattHours(std::string name, std::string units, int value) { return SignalLogger::WriteDouble(name, value, units, units::time::second_t(0.0_s)); }
	auto LogClimberManagerState(std::string name, std::string units, int value) { return SignalLogger::WriteDouble(name, value, units, units::time::second_t(0.0_s)); }
	ctre::phoenix::StatusCode LogExtender(string name, string units, double value) { return SignalLogger::WriteDouble(name, value, units, units::time::second_t(0.0_s)); }
	ctre::phoenix::StatusCode LogExtenderTarget(string name, string units, double value) { return SignalLogger::WriteDouble(name, value, units, units::time::second_t(0.0_s)); }
	ctre::phoenix::StatusCode LogExtenderPower(string name, string units, double value) { return SignalLogger::WriteDouble(name, value, units, units::time::second_t(0.0_s)); }
	ctre::phoenix::StatusCode LogExtenderEnergy(string name, string units, double value) { return SignalLogger::WriteDouble(name, value, units, units::time::second_t(0.0_s)); }
};