//====================================================================================================================================================
// Copyright 2025 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
// This file was automatically generated by the Team 302 code generator version 20.25.00.02
// Generated on Friday, January 24, 2025 8:21:52 PM

// C++ Includes
#include <string>

// FRC includes

// Team 302 includes
#include "mechanisms/DragonTale/L1ScoringPositionState.h"
#include "teleopcontrol/TeleopControl.h"
#include "teleopcontrol/TeleopControlFunctions.h"
#include "utils/logging/Logger.h"

// Third Party Includes

using namespace std;
using namespace DragonTaleStates;

/// @class ExampleForwardState
/// @brief information about the control (open loop, closed loop position, closed loop velocity, etc.) for a mechanism state
L1ScoringPositionState::L1ScoringPositionState(std::string stateName,
											   int stateId,
											   DragonTale *mech,
											   RobotIdentifier activeRobotId) : State(stateName, stateId), m_mechanism(mech), m_RobotId(activeRobotId)
{
}

void L1ScoringPositionState::Init()
{
	Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("L1ScoringPositionState"), string("Init"));

	if (m_RobotId == RobotIdentifier::PRACTICE_BOT_9999)
		InitPRACTICE_BOT9999();
}

void L1ScoringPositionState::InitPRACTICE_BOT9999()
{
	m_mechanism->UpdateTargetCoralPercentOutput(m_CoralTarget);
	m_mechanism->UpdateTargetAlgaePercentOutput(m_AlgaeTarget);
	m_mechanism->SetElevatorTarget(m_ElevatorLeaderTarget);
	m_mechanism->SetArmTarget(m_ArmTarget);
}

void L1ScoringPositionState::Run()
{
	// Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("L1ScoringPositionState"), string("Run"));
	if (m_mechanism->GetAlgaeSensorState())
		m_mechanism->UpdateTargetAlgaePercentOutput(0.05);
}

void L1ScoringPositionState::Exit()
{
	// Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("L1ScoringPositionState"), string("Exit"));
}

bool L1ScoringPositionState::AtTarget()
{
	// Logger::GetLogger()->LogData(LOGGER_LEVEL::PRINT, string("ArrivedAt"), string("L1ScoringPositionState"), string("AtTarget"));

	bool atTarget = false;
	return atTarget;
}

bool L1ScoringPositionState::IsTransitionCondition(bool considerGamepadTransitions)
{
	// To get the current state use m_mechanism->GetCurrentState()

	return (considerGamepadTransitions && (TeleopControl::GetInstance()->IsButtonPressed(TeleopControlFunctions::L1_SCORING_POSITION)) && m_mechanism->IsCoralMode());
}
