# workflow for validating auton xml

name: xml validation

on:
  push:
    # Run on pushes that modify XML files
    paths:
      - '**/*.xml'
  pull_request:
    paths:
      - '**/*.xml'

jobs:
  validate-xml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Validate XML Files
        run: |
          # Loop through each XML file in the repository
          for file in $(find . -type f -name '*.xml'); do
            echo "Validating ${file}"
            # If your XML file already includes a DOCTYPE declaration referencing your DTD,
            # xmllint will use it automatically. Otherwise, specify the DTD file with --dtdvalid.
            # Example if specifying a DTD (adjust the path as needed):
            # xmllint --noout --dtdvalid path/to/your.dtd "$file"
            xmllint --noout "$file"
          done